import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const snapshotPath = path.join(dir, "src/provider/models-snapshot.js")

async function readBundledSnapshot() {
  const marker = "export const snapshot = "
  const existing = await Bun.file(snapshotPath).text()
  const index = existing.indexOf(marker)
  if (index === -1) throw new Error(`Could not parse bundled models snapshot at ${snapshotPath}`)
  return existing.slice(index + marker.length).trim()
}

async function fetchModelsSnapshot() {
  if (process.env.MODELS_DEV_API_JSON) return await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  if (process.env.OPENCODE_DISABLE_MODELS_FETCH) return await readBundledSnapshot()

  const timeoutMs = Number(process.env.OPENCODE_MODELS_FETCH_TIMEOUT_MS ?? 5000)
  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), timeoutMs)
  try {
    const response = await fetch(`${modelsUrl}/api.json`, { signal: controller.signal })
    if (!response.ok) throw new Error(`models.dev responded with HTTP ${response.status}`)
    return await response.text()
  } catch (error) {
    console.warn(
      `Failed to fetch ${modelsUrl}/api.json within ${timeoutMs}ms; using bundled models snapshot instead.`,
      error,
    )
    return await readBundledSnapshot()
  } finally {
    clearTimeout(timeout)
  }
}

// Fetch and generate models.dev snapshot
const modelsData = await fetchModelsSnapshot()
JSON.parse(modelsData)
await Bun.write(
  snapshotPath,
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")
